#!/usr/bin/with-contenv bash
umask 002

dtach -n /detach_sess/.dtach s6-setuidgid abc /usr/bin/rtorrent -n -o import=/config/rtorrent/rtorrent.rc

until [ -e "/config/rtorrent/rtorrent_sess/rtorrent.lock" ];
do
sleep 1s
done

rtorrent_pid=$(cat /config/rtorrent/rtorrent_sess/rtorrent.lock | cut -d '+' -f 2)
tail -n 1 -f /config/log/rtorrent/rtorrent.log "$rtorrent_pid"
