#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config{/log/nginx,/log/rtorrent,/log/rutorrent,/nginx,/php,/rtorrent/rtorrent_sess,/rutorrent/settings/users} \
	/config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/config/themes \
	/downloads{/completed,/incoming,/watched} \
	/run{/nginx,/php} \
	/var/lib/nginx/tmp/client_body \
	/var/tmp/nginx


# copy config
PREV_DIR=$(pwd)

cd /defaults/rutorrent-conf || exit
	shopt -s globstar nullglob
	for i in *
	do
		[[ ! -e "/config/rutorrent/settings/${i}" ]] && cp -v "${i}" "/config/rutorrent/settings/${i}"
	done

cd "${PREV_DIR}" || exit

[[ ! -e /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf


[[ ! -e /config/rtorrent/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /config/rtorrent/rtorrent.rc
cp -pr /config/rutorrent/settings/* /usr/share/webapps/rutorrent/conf/

if [ ! -e "/config/php/php.ini" ]; then
	cp /etc/php7/php.ini /config/php/php.ini
	sed -i -e 's/\(register_argc_argv .*=\).*/\1 On/g' /config/php/php.ini
fi

cp /config/php/php.ini /etc/php7/php.ini

# create symlink for webui files
[[ ! -e /var/www/localhost/rutorrent ]] && ln -s \
/usr/share/webapps/rutorrent /var/www/localhost/rutorrent

# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent/rtorrent_sess/rtorrent.lock

# custom themes
[[ ! -L /usr/share/webapps/rutorrent/plugins/theme/themes ]] && \
	cp -R /usr/share/webapps/rutorrent/plugins/theme/themes/* /config/themes/
rm -rf /usr/share/webapps/rutorrent/plugins/theme/themes
ln -s /config/themes /usr/share/webapps/rutorrent/plugins/theme/themes

# permissions
chown abc:abc \
	/downloads \
	/downloads{/completed,/incoming,/watched}

chown -R abc:abc \
	/config \
	/run \
	/usr/share/webapps/rutorrent \
	/var/lib/nginx \
	/var/tmp/nginx \
	/var/www/localhost/rutorrent

chmod -R 755 /config/rutorrent/profiles
chmod 644 /etc/logrotate.d/*
