#!/usr/bin/with-contenv bash

echo '
*************************************************************
*************************************************************
*                                                           *
*                                                           *
*             This image has been deprecated                *
*                                                           *
*                 Use crazy-max's image at                  *
*                                                           *
*           crazy-max/docker-rtorrent-rutorrent             *
*                                                           *
*   https://hub.docker.com/r/crazymax/rtorrent-rutorrent/   *
*                                                           *
*  https://github.com/crazy-max/docker-rtorrent-rutorrent   *
*                                                           *
*                                                           *
*                                                           *
*************************************************************
*************************************************************'
